#!/usr/bin/env bash
set -euo pipefail

# One-time setup: named Cloudflare Tunnel for your domain (no modem port-forward).
#
#   bash docker/setup-named-tunnel.sh
#
# Prerequisites:
#   - dntechx.com added to Cloudflare (nameservers already active)
#   - Browser available for Cloudflare login (or CF_TUNNEL_TOKEN set)
#
# After this succeeds, run:
#   bash docker/install-cloudflare-tunnel.sh

DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "${DIR}/.." && pwd)"
BIN="${DIR}/bin/cloudflared"
CF_DIR="${HOME}/.cloudflared"
CONF_DIR="${DIR}/cloudflared"
CONF_FILE="${CONF_DIR}/config.yml"
ENV_FILE="${DIR}/cloudflared.env"

# shellcheck disable=SC1090
source "${ENV_FILE}"

ensure_cloudflared() {
  local arch cf_arch need_download=false
  arch="$(uname -m)"
  case "${arch}" in
    aarch64|arm64) cf_arch=arm64 ;;
    armv7l|armv6l) cf_arch=arm ;;
    x86_64|amd64) cf_arch=amd64 ;;
    *) echo "[tunnel] unsupported architecture: ${arch}"; exit 1 ;;
  esac

  if [[ -x "${BIN}" ]]; then
    if ! file "${BIN}" | grep -qiE "${cf_arch}|x86-64|x86_64|Intel 80386|ARM aarch64|ARM"; then
      need_download=true
    elif ! "${BIN}" --version >/dev/null 2>&1; then
      need_download=true
    fi
  else
    need_download=true
  fi

  # Detect wrong-arch binary (e.g. aarch64 binary on x86_64).
  if [[ -x "${BIN}" ]] && ! "${BIN}" --version >/dev/null 2>&1; then
    echo "[tunnel] existing cloudflared is not runnable on this host — re-downloading ${cf_arch}"
    need_download=true
  fi

  if [[ "${need_download}" == true ]]; then
    echo "[tunnel] downloading cloudflared (${cf_arch})…"
    mkdir -p "${DIR}/bin"
    curl -fsSL "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-${cf_arch}" -o "${BIN}"
    chmod +x "${BIN}"
  fi

  "${BIN}" --version
}

write_config() {
  local tunnel_id="$1"
  local creds="${CF_DIR}/${tunnel_id}.json"
  if [[ ! -f "${creds}" ]]; then
    echo "[tunnel] ERROR: credentials not found at ${creds}"
    exit 1
  fi

  mkdir -p "${CONF_DIR}"
  cat > "${CONF_FILE}" <<EOF
# Generated by docker/setup-named-tunnel.sh — do not commit credentials.
tunnel: ${tunnel_id}
credentials-file: ${creds}

# This network drops/blocks QUIC (UDP 7844) and has no working IPv6 egress,
# so pin the edge connection to HTTP/2 over IPv4.
protocol: http2
edge-ip-version: "4"

ingress:
  - hostname: ${TUNNEL_HOSTNAME}
    service: ${TUNNEL_UPSTREAM}
  - hostname: ${TUNNEL_HOSTNAME_WWW}
    service: ${TUNNEL_UPSTREAM}
  - service: http_status:404
EOF
  echo "[tunnel] wrote ${CONF_FILE}"
}

route_dns() {
  local tunnel_name="$1"
  echo "[tunnel] routing DNS ${TUNNEL_HOSTNAME} → tunnel ${tunnel_name}"
  "${BIN}" tunnel route dns --overwrite-dns "${tunnel_name}" "${TUNNEL_HOSTNAME}" || true
  echo "[tunnel] routing DNS ${TUNNEL_HOSTNAME_WWW} → tunnel ${tunnel_name}"
  "${BIN}" tunnel route dns --overwrite-dns "${tunnel_name}" "${TUNNEL_HOSTNAME_WWW}" || true
}

sync_app_base_url() {
  local prod_env="${DIR}/.env.prod"
  if [[ ! -f "${prod_env}" ]]; then
    echo "[tunnel] no ${prod_env} yet — APP_BASE_URL will be set on first deploy"
    echo "         expected: APP_BASE_URL=${APP_BASE_URL}"
    return 0
  fi
  if grep -q '^APP_BASE_URL=' "${prod_env}"; then
    sed -i "s|^APP_BASE_URL=.*|APP_BASE_URL=${APP_BASE_URL}|" "${prod_env}"
  else
    printf '\nAPP_BASE_URL=%s\n' "${APP_BASE_URL}" >> "${prod_env}"
  fi
  echo "[tunnel] APP_BASE_URL=${APP_BASE_URL}"
}

# ── Token-based path (Zero Trust dashboard → Create Tunnel → copy token) ──
if [[ -n "${CF_TUNNEL_TOKEN:-}" ]]; then
  echo "==> Using CF_TUNNEL_TOKEN (dashboard token install)"
  ensure_cloudflared
  mkdir -p "${CONF_DIR}"
  # Token mode does not need config.yml; service runs with --token.
  printf '%s\n' "${CF_TUNNEL_TOKEN}" > "${CONF_DIR}/tunnel.token"
  chmod 600 "${CONF_DIR}/tunnel.token"
  echo "[tunnel] saved token to ${CONF_DIR}/tunnel.token"
  sync_app_base_url
  echo
  echo "Token saved. Next:"
  echo "  1. In Cloudflare Zero Trust → Networks → Tunnels, add public hostnames:"
  echo "       ${TUNNEL_HOSTNAME}  → ${TUNNEL_UPSTREAM}"
  echo "       ${TUNNEL_HOSTNAME_WWW} → ${TUNNEL_UPSTREAM}"
  echo "  2. bash docker/install-cloudflare-tunnel.sh"
  exit 0
fi

echo "==> Ensuring cloudflared is installed"
ensure_cloudflared

mkdir -p "${CF_DIR}" "${CONF_DIR}"

if [[ ! -f "${CF_DIR}/cert.pem" ]]; then
  echo
  echo "==> Cloudflare login required"
  echo "    A browser window / URL will open. Authorize the ${TUNNEL_HOSTNAME} zone."
  echo
  "${BIN}" tunnel login
fi

echo "==> Creating or reusing tunnel '${TUNNEL_NAME}'"
EXISTING_ID="$("${BIN}" tunnel list -o json 2>/dev/null | python3 -c "
import json,sys
name='${TUNNEL_NAME}'
try:
  data=json.load(sys.stdin)
except Exception:
  data=[]
for t in data if isinstance(data,list) else data.get('tunnels',data) if isinstance(data,dict) else []:
  if isinstance(t,dict) and t.get('name')==name:
    print(t.get('id') or t.get('ID') or '')
    break
" 2>/dev/null || true)"

if [[ -n "${EXISTING_ID}" ]]; then
  TUNNEL_ID="${EXISTING_ID}"
  echo "[tunnel] reusing existing tunnel id=${TUNNEL_ID}"
else
  "${BIN}" tunnel create "${TUNNEL_NAME}"
  TUNNEL_ID="$("${BIN}" tunnel list -o json | python3 -c "
import json,sys
name='${TUNNEL_NAME}'
data=json.load(sys.stdin)
for t in data if isinstance(data,list) else []:
  if t.get('name')==name:
    print(t.get('id','')); break
")"
  if [[ -z "${TUNNEL_ID}" ]]; then
    # Fallback: parse from credentials files / list text
    TUNNEL_ID="$("${BIN}" tunnel list | awk -v n="${TUNNEL_NAME}" '$0 ~ n {print $1; exit}')"
  fi
  echo "[tunnel] created tunnel id=${TUNNEL_ID}"
fi

if [[ -z "${TUNNEL_ID}" ]]; then
  echo "[tunnel] ERROR: could not resolve tunnel id for ${TUNNEL_NAME}"
  "${BIN}" tunnel list
  exit 1
fi

printf '%s\n' "${TUNNEL_ID}" > "${CONF_DIR}/tunnel.id"
write_config "${TUNNEL_ID}"
route_dns "${TUNNEL_NAME}"
sync_app_base_url

echo
echo "==> Named tunnel ready"
echo "    Domain:  https://${TUNNEL_HOSTNAME}"
echo "    Tunnel:  ${TUNNEL_NAME} (${TUNNEL_ID})"
echo "    Config:  ${CONF_FILE}"
echo
echo "Next: bash docker/install-cloudflare-tunnel.sh"
echo
echo "You can remove modem/router port-forwards for 8080/8443 — traffic goes"
echo "through Cloudflare Tunnel outbound only (no inbound ports needed)."
