import type { RowDataPacket } from "mysql2/promise";
import type { PostFormat, PostVisibility } from "../../../types/post";

export interface PostRow extends RowDataPacket {
  id: string;
  user_id: string;
  body: string;
  format: PostFormat | null;
  title: string | null;
  visibility: PostVisibility;
  category_id: string | null;
  font_family: string | null;
  text_color: string | null;
  shared_post_id: string | null;
  translation_group_id: string | null;
  content_locale: string | null;
  created_at: string;
  updated_at: string;
  author_name: string | null;
  author_email: string;
  author_avatar_upload_id: string | null;
  author_title: string | null;
  author_job: string | null;
  author_location: string | null;
  comment_count: number;
  category_slug: string | null;
  category_name: string | null;
  category_sort_order: number | null;
  shared_body: string | null;
  shared_title: string | null;
  shared_format: PostFormat | null;
  shared_created_at: string | null;
  shared_author_id: string | null;
  shared_author_name: string | null;
  shared_author_email: string | null;
  shared_author_avatar_upload_id: string | null;
  shared_author_title: string | null;
  shared_author_job: string | null;
  shared_author_location: string | null;
}
