import dayjs, { type Dayjs, type ManipulateType } from "dayjs";
import { RecurrenceRule, type Task, type TimeBlock } from "~/types/task";

const UNIT: Record<RecurrenceRule, ManipulateType> = {
  [RecurrenceRule.Daily]: "day",
  [RecurrenceRule.Weekly]: "week",
  [RecurrenceRule.Monthly]: "month",
};

/**
 * Cap projection emission so a misconfigured rule (e.g. `daily / interval 1`
 * paired with a multi-month window) can never produce thousands of ghosts.
 */
const MAX_PROJECTIONS_PER_BLOCK = 365;

/**
 * Given a task with a `recurrence` rule, returns synthetic future TimeBlocks
 * that fall within `[windowStart, windowEnd]`. Each projection is marked with
 * `projected: true` so calendar views can render it as a ghost and so the
 * server-side sanitizer can refuse to persist it.
 *
 * The task's existing `timeBlocks` are treated as seeds; the projection is
 * generated by adding `interval * unit` to each seed and stopping once the
 * occurrence crosses `windowEnd` or the rule's `until` date.
 */
export function expandRecurrence(
  task: Task,
  windowStart: Dayjs,
  windowEnd: Dayjs
): TimeBlock[] {
  const r = task.recurrence;
  if (!r || !task.timeBlocks?.length) return [];
  if (!windowStart.isValid() || !windowEnd.isValid()) return [];

  const unit = UNIT[r.rule];
  const interval = Math.max(1, Math.round(r.interval));
  const until = r.until ? dayjs(r.until).endOf("day") : null;

  const projections: TimeBlock[] = [];

  for (const seed of task.timeBlocks) {
    const seedStart = dayjs(seed.start);
    const seedEnd = dayjs(seed.end);
    if (!seedStart.isValid() || !seedEnd.isValid()) continue;
    if (seedEnd.isBefore(seedStart)) continue;

    for (let n = 1; n <= MAX_PROJECTIONS_PER_BLOCK; n++) {
      const occStart = seedStart.add(n * interval, unit);
      const occEnd = seedEnd.add(n * interval, unit);

      // Past the rule's terminal date — done with this seed.
      if (until && occStart.isAfter(until)) break;
      // Past the visible window — also done.
      if (occStart.isAfter(windowEnd)) break;
      // Before the window — skip but keep walking.
      if (occEnd.isBefore(windowStart)) continue;

      projections.push({
        id: `${seed.id}__r${n}`,
        start: occStart.toISOString(),
        end: occEnd.toISOString(),
        projected: true,
      });
    }
  }

  return projections;
}

/**
 * Returns a derived task list where each recurring task has its `timeBlocks`
 * extended with projected ghosts for the given window. Non-recurring tasks
 * pass through untouched.
 */
export function withProjections(
  tasks: Task[],
  windowStart: Dayjs,
  windowEnd: Dayjs
): Task[] {
  return tasks.map((t) => {
    if (!t.recurrence) return t;
    const ghosts = expandRecurrence(t, windowStart, windowEnd);
    if (ghosts.length === 0) return t;
    return { ...t, timeBlocks: [...(t.timeBlocks ?? []), ...ghosts] };
  });
}

export const useRecurrence = () => {
  return { expandRecurrence, withProjections };
};
